---
# Source: weatherapp-auth/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-weatherapp-auth
  labels:
    helm.sh/chart: weatherapp-auth-0.1.0
    app.kubernetes.io/name: weatherapp-auth
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: weatherapp-auth/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-weatherapp-auth
  labels:
    helm.sh/chart: weatherapp-auth-0.1.0
    app.kubernetes.io/name: weatherapp-auth
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: weatherapp-auth
    app.kubernetes.io/instance: release-name
---
# Source: weatherapp-auth/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-weatherapp-auth
  labels:
    helm.sh/chart: weatherapp-auth-0.1.0
    app.kubernetes.io/name: weatherapp-auth
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: weatherapp-auth
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-auth
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-weatherapp-auth
      securityContext:
        {}
      containers:
        - name: weatherapp-auth
          securityContext:
            {}
          image: "afakharany/weatherapp-auth:0.0.1"
          imagePullPolicy: IfNotPresent
          env:
          - name: DB_HOST
            value: mysql
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: weatherapp-auth/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-weatherapp-auth-test-connection"
  labels:
    helm.sh/chart: weatherapp-auth-0.1.0
    app.kubernetes.io/name: weatherapp-auth
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-weatherapp-auth:8080']
  restartPolicy: Never
